apiVersion: v1
kind: Service
metadata:
  name: docker-image-registry-service
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-protocol: "https"
    service.beta.kubernetes.io/do-loadbalancer-tls-ports: "5000"
    service.beta.kubernetes.io/do-loadbalancer-certificate-id: "783488f3-083b-45e9-b6c9-bf650de41e9e"
    service.beta.kubernetes.io/do-loadbalancer-disable-lets-encrypt-dns-records: "false"
    service.beta.kubernetes.io/do-loadbalancer-name: "docker-image-registry"
spec:
  type: LoadBalancer
  selector:
    app: docker-image-registry
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
