apiVersion: v1
kind: ServiceAccount
metadata:
  name: nova-provisioner
  namespace: default
---
apiVersion: v1
kind: Secret
metadata:
  name: nova-provisioner-token
  namespace: default
  annotations:
    kubernetes.io/service-account.name: nova-provisioner
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nova-provisioner
subjects:
  - kind: ServiceAccount
    name: nova-provisioner
    namespace: default
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
